GEMINI_API_KEY ="AIzaSyCtGgQUPNIGUYjb2V86jEzGtNhAULFpapA"
SUPABASE_URL ="https://anwszmsxyliotsjgmnwg.supabase.co"
SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFud3N6bXN4eWxpb3RzamdtbndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTcxNzgsImV4cCI6MjA2NTEzMzE3OH0.loxpP3sKslBMcpWho_Kwjp6QqX8507kdheKEej7ti64"